### ISSUE TITLE
urllib3.exceptions.MaxRetryError:

### ISSUE THREAD

**Issue by kalungia** [badsyntax/mailinabox-api-py#18]
Good day,
I have been trying to solve this for a long time but I am stack on the error bellow 

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Odoo\15\python\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000020BE23EB448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Odoo\15\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Odoo\15\server\odoo\http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "C:\Odoo\15\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Odoo\15\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Odoo\15\server\odoo\http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Odoo\15\server\odoo\http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "C:\Odoo\15\server\odoo\http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "C:\Odoo\15\server\odoo\addons\web\controllers\main.py", line 1352, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Odoo\15\server\odoo\addons\web\controllers\main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Odoo\15\server\odoo\api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Odoo\15\server\odoo\api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\users\user\documents\addons\imbra\imbra_hosting\models\host_order.py", line 377, in approve_account
    self.add_mail_user_domain()
  File "c:\users\user\documents\addons\imbra\imbra_hosting\models\host_order.py", line 548, in add_mail_user_domain
    api_response = api_instance.add_mail_user(email, password, privileges)
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\api\mail_api.py", line 62, in add_mail_user
    email, password, privileges, **kwargs
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\api\mail_api.py", line 191, in add_mail_user_with_http_info
    collection_formats=collection_formats,
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\api_client.py", line 413, in call_api
    _host,
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\api_client.py", line 204, in __call_api
    _request_timeout=_request_timeout,
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\api_client.py", line 481, in request
    body=body,
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\rest.py", line 343, in POST
    body=body,
  File "C:\Odoo\15\python\lib\site-packages\mailinabox_api\rest.py", line 191, in request
    headers=headers,
  File "C:\Odoo\15\python\lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\poolmanager.py", line 324, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Odoo\15\python\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Odoo\15\python\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Odoo\15\server\odoo\http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Odoo\15\server\odoo\http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='box.example.com', port=443): Max retries exceeded with url: /admin/mail/users/add (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020BE23EB448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by badsyntax** [comment]
it looks like it's trying to hit box.example.com, so you need to update the host: https://github.com/badsyntax/mailinabox-api-py#getting-started

**Comment by kalungia** [comment]
Hey here is my code, i changed it but I don't understand why it is using box.example.com

#import mailinabox_api
#from mailinabox_api.rest import ApiException

            
        # configuration = mailinabox_api.Configuration(host = "mybox.com")
        # configuration = mailinabox_api.Configuration(username = myusername, password = mypassword)
        
        # # Enter a context with an instance of the API client
        # with mailinabox_api.ApiClient(configuration) as api_client:
            # # Create an instance of the API class
            # api_instance = mailinabox_api.MailApi(api_client)
            # email = "info@abnetw.com"
            # password = self.name 
            # privileges = mailinabox_api.MailUserPrivilege()

            # try:
                # api_response = api_instance.add_mail_user(email, password, privileges)
                # self.web_error_msg = api_response
            # except ApiException as e:
                # self.web_error_msg = str(e)

**Comment by badsyntax** [comment]
i think the (auto-generated) docs are a little confusing, i think it needs to be:

```py
configuration = mailinabox_api.Configuration(
    username = 'YOUR_USERNAME',
    password = 'YOUR_PASSWORD',
    host = "mybox.com"
)
```

(ie, only define the configuration once)

**Comment by kalungia** [comment]
Hey, I have done as you have said and it is working thank you very much

        # configuration = mailinabox_api.Configuration(host = "mybox.com")
        configuration = mailinabox_api.Configuration(username = myusername, password = mypassword, host = "mybox.com")
